Failure # 1 (occurred at 2025-04-25_14-40-48)
[36mray::ImplicitFunc.train()[39m (pid=49373, ip=10.33.20.59, actor_id=527d9a64bbda968a00d1e0b401000000, repr=tune_train_func)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/shyam/PycharmProjects/Softmax/.venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
    output = fn()
  File "/home/shyam/PycharmProjects/Softmax/train.py", line 103, in tune_train_func
    x, targets = generate_data(config["batch_size"], input_dim)
  File "/home/shyam/PycharmProjects/Softmax/train.py", line 29, in generate_data
    logits = torch.randn(batch_size, **input_dim)
TypeError: torch._VariableFunctionsClass.randn() argument after ** must be a mapping, not tuple
